### ISSUE TITLE
some previews are failing

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/km-template#2]
Hello @MarekSuchanek: just tested this version. I had a quick look at the csv output, looks impressive --I would need some time to study.

Of all the possible outputs, only cvs and opml are successful. Everything else fail with 

dsw_server_1  | 2021-09-14T08:40:51.344390315Z [Warn ] [I:4f9a9661-d4c2-4f17-ab76-f382d826e67] [T:------------------------------------] [API         ] 400 Bad Request HAD /questionnaires/7650dce9-6f05-4dbc-adf1-b4d60437355e/documents/preview

So I am not sure if it is on my side or???
Thanks!

**Comment by froggypaule** [comment]
actually, I am still at 3.2.0; will confirm if this persist once upgraded to 3.3.0

**Comment by froggypaule** [comment]
now, DSW 3.3.0:

- for HTML Table:

 Failed to build final document
 Exception: FormatStepException
 Message: Failed rendering Jinja2 template due to UndefinedError
 'renderPhase' is undefined

- for HTML List and MW word list:

 Failed to build final document
 Exception: ValueError
 Message: unconverted data remains: Z

- CSV: ok
- OPML: ok


It could be well my 'fault' since again the km is generated programmatically and there might be fields missing. If you think this is the case I won't bother you further  with this issue.

**Comment by froggypaule** [comment]
Ok, for KM Common DSW Knowledge Model, there is only one bug appearing:

    for HTML Table:

Failed to build final document
Exception: FormatStepException
Message: Failed rendering Jinja2 template due to UndefinedError
'renderPhase' is undefined

Everything else works.

**Comment by MarekSuchanek** [comment]
Thanks for reporting! Will check...

**Comment by MarekSuchanek** [comment]
There were some missing macros... please try with https://github.com/ds-wizard/km-insight-template/releases/tag/v0.4.1

**Comment by froggypaule** [comment]
Good morning Marek: we are not quite there yet (testing with dsw common KM) 
![Screenshot from 2021-09-17 08-55-06](https://user-images.githubusercontent.com/47455219/133738327-46e7c77d-dfd6-48aa-9573-7b03f8556509.png)

I just replaced template.json with its new version.

**Comment by MarekSuchanek** [comment]
That won't work... you need to re-import the template as a ZIP file.

**Comment by froggypaule** [comment]
you mean importing from the GUI?
I downloaded the zip file and used dst-tdk to push/import...

I'll retry.

**Comment by MarekSuchanek** [comment]
Yes, the `template.zip` should be imported using GUI. That is the easiest way...

Or you can clone the repository (or unzip `Source code (zip)`) and then use `dsw-tdk put`. The content of those two ZIP files is different...

**Comment by froggypaule** [comment]
- yep, via the GUI, all good;
- but via dsw-tdk, I had a README file missing 
![Screenshot from 2021-09-17 12-32-10](https://user-images.githubusercontent.com/47455219/133768902-9c6a1ca4-3b4e-4da3-9799-748299d0cf18.png)
Once I copied one over it worked.

Now, I tested this:
- now dsw:root:2.3.0 works perfectly, as you would expect (!)
- but not my own KM

I would appreciate if you could shed some light on it; I guess there are missing fields somewhere....:
- HTML list fails with 
![Screenshot from 2021-09-17 12-36-08](https://user-images.githubusercontent.com/47455219/133769347-8ac46594-3e5d-41fc-b1ee-508dec50c7bd.png)
- as does MS Word list
- but OPML, CSV, and HTML Table work 

why HTML Table and not List? I guess it must be because of the respective fields involved

Finally. I guess in the future one can bring some improvements to this output (uuids are not necessarily useful in the Word document, etc...), but this is another conversation.

Thanks!

**Comment by MarekSuchanek** [comment]
Hmmm... it seems that it has an issue with parsing some timestamp, it probably expects UTC timestamp ending with `Z`, but that's in document worker filter. In the next release, I will be enhancing filters so I note this done to look at it.

(HTML and Word "list" are made using the same Jinja template file, but HTML table uses a different one)
https://github.com/ds-wizard/km-insight-template/blob/insight/src/html-list/template.html.j2#L216
